l_simp_chinese:
 MESSAGE_SETTINGS_WINDOW_NAME: "消息设置"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\n按筛选组编辑信息的频率和可见度。"
 MESSAGE_SETTINGS_WINDOW_RESET: "重置为默认状态"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T 重置消息设置#!\n#I 点击将当前更改重置为默认设定#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "应用更改"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I 点击关闭消息设置窗口并保存现有更改#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon!消息"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon!提示框"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon!弹出"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon!永不"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "筛选组"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "消息筛选组名称"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "外观"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "如何显示此筛选组的消息"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "暂停"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "该类别信息出现时游戏是否暂停"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T 切换自动暂停#!\n#I 切换为当该筛选组的信息出现时自动暂停#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T 关闭信息#!\n#I 点击关闭当前信息，显示队列中的下一条信息#!"
