l_spanish:
 MESSAGE_SETTINGS_WINDOW_NAME: "Configuración de mensajes"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nEditar la frecuencia y visibilidad de los mensajes filtradas por grupos."
 MESSAGE_SETTINGS_WINDOW_RESET: "Predeterminada"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Reiniciar la configuración de mensajes#!\n#I Haz clic para reiniciar a la configuración predeterminada#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Aplicar cambios"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Haz clic para cerrar la pantalla de configuración de mensajes y guardar los cambios#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Noticias"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Notificaciones"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Ventana emergente"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Nunca"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Grupo de filtrado"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Nombre del grupo de filtrado de mensajes"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Aspecto"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "Cómo aparecerán los mensajes de este grupo de filtrado"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Pausa"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "Indica si la partida debe entrar en pausa cuando aparezcan mensajes de este filtro"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Activar autopausa#!\n#I Activa esta opción para pausar la partida cuando aparezcan mensajes de este filtro#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Descartar mensaje#!\n#I Haz clic para descartar el mensaje actual y mostrar el siguiente de la cola#!"
