l_german:
 MESSAGE_SETTINGS_WINDOW_NAME: "Nachrichteneinstellungen"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nHäufigkeit und Anzeige von Nachrichten nach gefilterten Gruppen anpassen."
 MESSAGE_SETTINGS_WINDOW_RESET: "Auf Standard zurücksetzen"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Nachrichteneinstellungen zurücksetzen#!\n#I Klicken, um die derzeitigen Änderungen auf den Standard zurückzusetzen#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Änderungen anwenden"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Klicken, um das Fenster der Nachrichteneinstellungen zu schließen und die derzeitigen Änderungen zu speichern#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Feed"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Toast"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Popup"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Nie"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Filtergruppe"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Name der Nachrichtenfiltergruppe"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Aussehen"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "Wie Nachrichten dieser Filtergruppe angezeigt werden"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Pausieren"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "Ob das Spiel pausieren soll, wenn Nachrichten dieses Filters erscheinen"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Auto-Pause umschalten#!\n#I Klicken, um umzuschalten, ob das Spiel pausieren soll, wenn Nachrichten dieses Filters erscheinen#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Meldung verwerfen#!\n#I Klicken, um die derzeitige Meldung zu verwerfen und die nächste Meldung in der Warteschlange anzuzeigen#!"
