l_french:
 MESSAGE_SETTINGS_WINDOW_NAME: "Paramètres des messages"
 MESSAGE_SETTINGS_WINDOW_TT: "#T $MESSAGE_SETTINGS_WINDOW_NAME$#!\nModifiez la fréquence et la visibilité des messages par groupes filtrés."
 MESSAGE_SETTINGS_WINDOW_RESET: "Réinitialiser les paramètres"
 MESSAGE_SETTINGS_WINDOW_RESET_TT: "#T Réinitialiser les paramètres des messages#!\n#I Cliquez pour revenir aux paramètres par défaut#!"
 MESSAGE_SETTINGS_WINDOW_APPLY: "Appliquer les modifications"
 MESSAGE_SETTINGS_WINDOW_APPLY_TT: "#T $MESSAGE_SETTINGS_WINDOW_APPLY$#!\n#I Cliquez pour fermer la fenêtre Paramètres des messages et enregistrer les modifications actuelles#!"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_FEED: "@check_icon! Flux"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_TOAST: "@alert_icon! Toast"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_POPUP: "@opinion_icon! Popup"
 MESSAGE_SETTINGS_WINDOW_APPEARANCE_HIDDEN: "@cross_icon! Jamais"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE: "Groupe de filtres"
 MESSAGE_SETTINGS_WINDOW_COLUMN_FILTER_TYPE_TT: "Nom du groupe de filtres de messages"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE: "Apparence"
 MESSAGE_SETTINGS_WINDOW_COLUMN_APPEARANCE_TT: "Comment afficher les messages de ce groupe de filtres"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE: "Mettre en pause"
 MESSAGE_SETTINGS_WINDOW_COLUMN_AUTO_PAUSE_TT: "Si le jeu doit se mettre en pause lorsque les messages de ce filtre apparaissent"
 MESSAGE_SETTINGS_WINDOW_TOGGLE_AUTO_PAUSE_TT: "#T Activer la pause automatique#!\n#I Mettre le jeu en pause lorsque les messages de ce filtre apparaissent#!"
 MESSAGE_SETTINGS_WINDOW_CLOSE_POPUP: "#T Ignorer le message#!\n#I Cliquer pour ignorer le message actuel et afficher le message suivant dans la file d’attente#!"
